export const WORD_BANK = [
  { en: "pizza", ru: "пицца" },
  { en: "burger", ru: "бургер" },
  { en: "rocket", ru: "ракета" },
  { en: "castle", ru: "замок" },
  { en: "banana", ru: "банан" },
  { en: "guitar", ru: "гитара" },
  { en: "car", ru: "машина" },
  { en: "bicycle", ru: "велосипед" },
  { en: "treasure", ru: "сокровище" },
  { en: "pirate", ru: "пират" },
  { en: "volcano", ru: "вулкан" },
  { en: "dragon", ru: "дракон" },
  { en: "robot", ru: "робот" },
  { en: "dinosaur", ru: "динозавр" },
  { en: "umbrella", ru: "зонт" },
  { en: "key", ru: "ключ" },
  { en: "crown", ru: "корона" },
  { en: "book", ru: "книга" },
  { en: "candle", ru: "свеча" },
  { en: "clock", ru: "часы" },
  { en: "camera", ru: "камера" },
  { en: "phone", ru: "телефон" },
  { en: "suitcase", ru: "чемодан" },
  { en: "ladder", ru: "лестница" },
  { en: "balloon", ru: "воздушный шар" },
  { en: "teapot", ru: "чайник" },
  { en: "cookie", ru: "печенье" },
  { en: "sandwich", ru: "сэндвич" },
  { en: "ice cream", ru: "мороженое" },
  { en: "donut", ru: "пончик" },
  { en: "violin", ru: "скрипка" },
  { en: "skateboard", ru: "скейтборд" },
  { en: "submarine", ru: "подводная лодка" },
  { en: "helicopter", ru: "вертолет" },
  { en: "train", ru: "поезд" },
  { en: "bus", ru: "автобус" },
  { en: "airplane", ru: "самолет" },
  { en: "anchor", ru: "якорь" },
  { en: "compass", ru: "компас" },
  { en: "telescope", ru: "телескоп" },
  { en: "map", ru: "карта" },
  { en: "backpack", ru: "рюкзак" },
  { en: "toothbrush", ru: "зубная щетка" },
  { en: "scissors", ru: "ножницы" },
  { en: "pillow", ru: "подушка" },
  { en: "mirror", ru: "зеркало" },
  { en: "ring", ru: "кольцо" },
  { en: "hat", ru: "шляпа" },
  { en: "boot", ru: "ботинок" },
  { en: "glove", ru: "перчатка" },
  { en: "lantern", ru: "фонарь" },
  { en: "hammer", ru: "молоток" },
  { en: "wrench", ru: "гаечный ключ" },
  { en: "magnet", ru: "магнит" },
  { en: "diamond", ru: "алмаз" },
  { en: "trophy", ru: "кубок" },
  { en: "medal", ru: "медаль" },
  { en: "helmet", ru: "шлем" },
  { en: "paintbrush", ru: "кисть" },
  { en: "pumpkin", ru: "тыква" },
  { en: "satellite", ru: "спутник" },
  { en: "dog", ru: "собака" },
  { en: "cat", ru: "кот" },
  { en: "penguin", ru: "пингвин" },
  { en: "elephant", ru: "слон" },
  { en: "giraffe", ru: "жираф" },
  { en: "shark", ru: "акула" },
  { en: "snake", ru: "змея" },
  { en: "owl", ru: "сова" },
  { en: "turtle", ru: "черепаха" },
  { en: "rabbit", ru: "кролик" },
  { en: "fox", ru: "лиса" },
  { en: "bear", ru: "медведь" },
  { en: "koala", ru: "коала" },
  { en: "octopus", ru: "осьминог" },
  { en: "whale", ru: "кит" },
  { en: "dolphin", ru: "дельфин" },
  { en: "frog", ru: "лягушка" },
  { en: "bee", ru: "пчела" },
  { en: "butterfly", ru: "бабочка" },
  { en: "horse", ru: "лошадь" },
  { en: "cow", ru: "корова" },
  { en: "pig", ru: "свинья" },
  { en: "chicken", ru: "курица" },
  { en: "duck", ru: "утка" },
  { en: "panda", ru: "панда" },
  { en: "crocodile", ru: "крокодил" },
  { en: "monkey", ru: "обезьяна" },
  { en: "camel", ru: "верблюд" },
  { en: "deer", ru: "олень" },
  { en: "wolf", ru: "волк" },
  { en: "unicorn", ru: "единорог" },
  { en: "phoenix", ru: "феникс" },
  { en: "rainbow", ru: "радуга" },
  { en: "sun", ru: "солнце" },
  { en: "moon", ru: "луна" },
  { en: "mountain", ru: "гора" },
  { en: "island", ru: "остров" },
  { en: "storm", ru: "шторм" },
  { en: "forest", ru: "лес" },
  { en: "river", ru: "река" },
  { en: "waterfall", ru: "водопад" },
  { en: "cloud", ru: "облако" },
  { en: "snowflake", ru: "снежинка" },
  { en: "lightning", ru: "молния" },
  { en: "flower", ru: "цветок" },
  { en: "cactus", ru: "кактус" },
  { en: "palm tree", ru: "пальма" },
  { en: "mushroom", ru: "гриб" },
  { en: "desert", ru: "пустыня" },
  { en: "ocean", ru: "океан" },
  { en: "beach", ru: "пляж" },
  { en: "leaf", ru: "лист" },
  { en: "fire", ru: "огонь" },
  { en: "rain", ru: "дождь" },
  { en: "tornado", ru: "торнадо" },
  { en: "iceberg", ru: "айсберг" },
  { en: "cave", ru: "пещера" },
  { en: "planet", ru: "планета" },
  { en: "comet", ru: "комета" },
  { en: "star", ru: "звезда" },
  { en: "love", ru: "любовь" },
  { en: "jealousy", ru: "ревность" },
  { en: "fear", ru: "страх" },
  { en: "surprise", ru: "удивление" },
  { en: "anger", ru: "злость" },
  { en: "happiness", ru: "счастье" },
  { en: "sadness", ru: "грусть" },
  { en: "confusion", ru: "замешательство" },
  { en: "pride", ru: "гордость" },
  { en: "embarrassment", ru: "смущение" },
  { en: "freedom", ru: "свобода" },
  { en: "chaos", ru: "хаос" },
  { en: "peace", ru: "мир" },
  { en: "luck", ru: "удача" },
  { en: "danger", ru: "опасность" },
  { en: "friendship", ru: "дружба" },
  { en: "boredom", ru: "скука" },
  { en: "curiosity", ru: "любопытство" },
  { en: "hope", ru: "надежда" },
  { en: "panic", ru: "паника" },
  { en: "first date", ru: "первое свидание" },
  { en: "falling in love", ru: "влюбиться" },
  { en: "argument", ru: "ссора" },
  { en: "apology", ru: "извинение" },
  { en: "celebration", ru: "празднование" },
  { en: "winning", ru: "победа" },
  { en: "losing", ru: "проигрыш" },
  { en: "awkward silence", ru: "неловкое молчание" },
  { en: "bad haircut", ru: "плохая стрижка" },
  { en: "late for work", ru: "опоздание на работу" },
  { en: "food coma", ru: "пищевая кома" },
  { en: "sleepy", ru: "сонный" },
  { en: "dreaming", ru: "мечтать" },
  { en: "running", ru: "бег" },
  { en: "jumping", ru: "прыжки" },
  { en: "dancing", ru: "танцы" },
  { en: "singing", ru: "пение" },
  { en: "crying", ru: "плач" },
  { en: "laughing", ru: "смех" },
  { en: "reading", ru: "чтение" },
  { en: "cooking", ru: "готовка" },
  { en: "painting", ru: "рисование" },
  { en: "fishing", ru: "рыбалка" },
  { en: "camping", ru: "поход" },
  { en: "surfing", ru: "серфинг" },
  { en: "skating", ru: "катание" },
  { en: "swimming", ru: "плавание" },
  { en: "hiding", ru: "прятки" },
  { en: "shopping", ru: "шопинг" },
  { en: "working", ru: "работа" },
  { en: "whispering", ru: "шепот" },
  { en: "sneezing", ru: "чихание" },
  { en: "hiccup", ru: "икота" },
  { en: "karaoke", ru: "караоке" },
  { en: "picnic", ru: "пикник" },
  { en: "proposal", ru: "предложение" },
  { en: "gossip", ru: "сплетни" },
  { en: "magic", ru: "магия" },
  { en: "ghost", ru: "призрак" },
  { en: "vampire", ru: "вампир" },
  { en: "wizard", ru: "волшебник" },
  { en: "knight", ru: "рыцарь" },
  { en: "queen", ru: "королева" },
  { en: "king", ru: "король" },
  { en: "mermaid", ru: "русалка" },
  { en: "alien", ru: "инопланетянин" },
  { en: "monster", ru: "монстр" },
  { en: "circus", ru: "цирк" },
  { en: "carnival", ru: "карнавал" },
  { en: "birthday cake", ru: "именинный торт" },
  { en: "wedding", ru: "свадьба" },
  { en: "school", ru: "школа" },
  { en: "library", ru: "библиотека" },
  { en: "hospital", ru: "больница" },
  { en: "bakery", ru: "пекарня" },
  { en: "market", ru: "рынок" },
  { en: "farm", ru: "ферма" },
  { en: "zoo", ru: "зоопарк" },
  { en: "museum", ru: "музей" },
  { en: "concert", ru: "концерт" },
  { en: "disco", ru: "дискотека" },
  { en: "traffic jam", ru: "пробка" },
  { en: "roller coaster", ru: "американские горки" },
  { en: "video game", ru: "видеоигра" },
  { en: "chess", ru: "шахматы" },
  { en: "puzzle", ru: "головоломка" },
  { en: "snowman", ru: "снеговик" },
  { en: "gift", ru: "подарок" },
  { en: "popcorn", ru: "попкорн" },
  { en: "noodles", ru: "лапша" },
  { en: "sushi", ru: "суши" },
  { en: "taco", ru: "тако" },
  { en: "watermelon", ru: "арбуз" },
  { en: "strawberry", ru: "клубника" },
  { en: "pineapple", ru: "ананас" },
  { en: "coconut", ru: "кокос" },
  { en: "avocado", ru: "авокадо" },
  { en: "cherry", ru: "вишня" },
  { en: "lemon", ru: "лимон" },
  { en: "pretzel", ru: "крендель" },
  { en: "pancakes", ru: "блины" },
  { en: "coffee", ru: "кофе" },
  { en: "milkshake", ru: "молочный коктейль" },
  { en: "soup", ru: "суп" },
  { en: "fries", ru: "картофель фри" },
  { en: "spaghetti", ru: "спагетти" },
  { en: "dumpling", ru: "пельмень" },
  { en: "sausage", ru: "сосиска" },
  { en: "cheese", ru: "сыр" },
  { en: "salad", ru: "салат" },
  { en: "hot air balloon", ru: "воздушный шар" },
  { en: "roller skates", ru: "ролики" },
  { en: "jellyfish", ru: "медуза" },
  { en: "starfish", ru: "морская звезда" },
  { en: "parrot", ru: "попугай" },
  { en: "peacock", ru: "павлин" },
  { en: "bat", ru: "летучая мышь" },
  { en: "hedgehog", ru: "еж" },
  { en: "squirrel", ru: "белка" },
  { en: "hamster", ru: "хомяк" },
  { en: "catnap", ru: "дневной сон" },
  { en: "moonwalk", ru: "лунная походка" },
  { en: "fireworks", ru: "фейерверк" },
  { en: "maze", ru: "лабиринт" },
  { en: "jungle", ru: "джунгли" },
  { en: "bridge", ru: "мост" },
  { en: "lighthouse", ru: "маяк" },
  { en: "igloo", ru: "иглу" },
  { en: "tent", ru: "палатка" },
  { en: "treasure chest", ru: "сундук с сокровищами" }
];

export function normalizeAnswer(value) {
  return String(value ?? "")
    .toLowerCase()
    .trim()
    .replace(/ё/g, "е")
    .replace(/[.,!?;:()"']/g, "")
    .replace(/\s+/g, " ");
}

export function formatWordPair(word) {
  if (!word) {
    return "";
  }

  return `${word.en} / ${word.ru}`;
}

export const WORD_BANK_COUNT = WORD_BANK.length;
